# -*- coding: utf-8 -*-
"""Face_pay.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IeW3ZWj6139BZU0IRrSl5rZ9yyTI0aaS
"""

import streamlit as st
import cv2
import face_recognition
import numpy as np

# Step 1: Load the known face and encoding
# Replace 'your_image.jpg' with the path to an image of the user you want to recognize
known_image = face_recognition.load_image_file("your_image.jpg")
known_face_encoding = face_recognition.face_encodings(known_image)[0]

# Initialize variables
face_match = False
attempt_code = ""

# Streamlit title
st.title("Facial Recognition App with Code Verification")

# Step 2: Webcam capture and facial recognition
st.write("Click the button to start webcam and scan your face.")
run = st.button("Start Camera")

if run:
    # Open the webcam
    video_capture = cv2.VideoCapture(0)

    while True:
        ret, frame = video_capture.read()

        # Convert the image from BGR to RGB
        rgb_frame = frame[:, :, ::-1]

        # Find all the faces in the current frame
        face_locations = face_recognition.face_locations(rgb_frame)
        face_encodings = face_recognition.face_encodings(rgb_frame, face_locations)

        for face_encoding in face_encodings:
            # Compare the captured face with the known face
            matches = face_recognition.compare_faces([known_face_encoding], face_encoding)
            face_distance = face_recognition.face_distance([known_face_encoding], face_encoding)
            best_match_index = np.argmin(face_distance)

            if matches[best_match_index]:
                face_match = True
                st.write("Face recognized! Please enter the code.")
                break

        # Display the frame in Streamlit
        frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        st.image(frame)

        if face_match:
            break

    video_capture.release()
    cv2.destroyAllWindows()

# Step 3: If face is recognized, ask for a code
if face_match:
    # Ask user to input code
    entered_code = st.text_input("Enter your security code", type="password")

    # Check the code
    correct_code = "1234"  # Set your desired code here
    if entered_code:
        if entered_code == correct_code:
            st.success("Code is correct! Access granted.")
        else:
            st.error("Incorrect code. Try again.")









